#!/bin/bash
mkdir webp

PARAMS=('-m 6 -q 75 -mt -af -progress')

if [ $# -ne 0 ]; then
        PARAMS=$@;
fi

#cd $(pwd)

shopt -s nullglob nocaseglob extglob

for FILE in *.@(jpg|jpeg|tif|tiff|png|bmp|gif); do
   cwebp $PARAMS "$FILE" -o "webp/${FILE%.*}".webp;
done


